[RabbitMQ]
host = localhost
#cambiarlo por redes2.ii.uam.es, nosotros solo lo podemos comprobar en localhost pues
#no tenemos ping a redes2.ii.uam.es
port = 5672
username = guest
password = guest

[Database]
path = data/saimazoom.db

[Logging]
level = INFO